### ISSUE TITLE
Convert Brian jpeg to png

### ISSUE THREAD

**Issue by epiro-ps** [ArdanaLabs/DanaSwapUI#98]
We'll want to convert Brian's avatar to a png to be consistent with the rest of the avatar files

https://github.com/ArdanaLabs/DanaSwapUI/pull/97/files#diff-dd9d497cd4c1cc4611c0586303d866f1d3f89ac64fb54b34bef9da372b4bfdca

**Comment by leomayleomay** [comment]
done with this commit https://github.com/ArdanaLabs/DanaSwapUI/pull/97/commits/eea73d5a26a36b3e7ae8a7c888f0359dc9b42bc8
